version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "php artisan serve --host 0.0.0.0"
    environment:
      - DB_HOST=db
      - DB_NAME=click-me_backend_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=click-me_backend_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
